ERROR:root:Se produjo un error: name 'dias_jobs_frame' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 725, in main
    actualizar_interfaz()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 645, in actualizar_interfaz
    for widget in dias_jobs_frame.winfo_children():
                  ^^^^^^^^^^^^^^^
NameError: name 'dias_jobs_frame' is not defined

ERROR:root:Se produjo un error: name 'seleccion_var' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 727, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 651, in actualizar_interfaz
    tk.Radiobutton(dias_jobs_frame, text="Seleccionar todos los días", variable=seleccion_var, value="todos_los_dias",
                                                                                ^^^^^^^^^^^^^
NameError: name 'seleccion_var' is not defined

ERROR:root:Se produjo un error: name 'dias_jobs_frame' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 712, in main
    titulo_label = tk.Label(dias_jobs_frame, text="Generador Mallas Reliabity", font=("Arial", 16, "bold"),
                            ^^^^^^^^^^^^^^^
NameError: name 'dias_jobs_frame' is not defined

ERROR:root:Se produjo un error: name 'dias_jobs_frame' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 712, in main
    titulo_label = tk.Label(dias_jobs_frame, text="Generador Mallas Reliabity", font=("Arial", 16, "bold"),
                            ^^^^^^^^^^^^^^^
NameError: name 'dias_jobs_frame' is not defined

ERROR:root:Se produjo un error: name 'lupa_photo' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 747, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 692, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 611, in interfaz_seleccion_job
    label_lupa = tk.Label(dias_jobs_frame, image=lupa_photo, bg="white")
                                                 ^^^^^^^^^^
NameError: name 'lupa_photo' is not defined

ERROR:root:Se produjo un error: can only concatenate str (not "int") to str
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 770, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 715, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 646, in interfaz_seleccion_job
    for job in job_listbox:
  File "C:\Users\Maxi\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1708, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
                                         ~~~~^~~~~
TypeError: can only concatenate str (not "int") to str

ERROR:root:Se produjo un error: name 'root' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 860, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 804, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 729, in interfaz_seleccion_job
    selected_jobs_listbox = tk.Listbox(root, selectmode=tk.MULTIPLE, width=50, height=7)
                                       ^^^^
NameError: name 'root' is not defined

ERROR:root:Se produjo un error: name 'root' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 860, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 804, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 729, in interfaz_seleccion_job
    selected_jobs_listbox = tk.Listbox(root, selectmode=tk.MULTIPLE, width=50, height=7)
                                       ^^^^
NameError: name 'root' is not defined

ERROR:root:Se produjo un error: bad 2nd pad value "-10": must be positive screen distance
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 866, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 810, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 735, in interfaz_seleccion_job
    scrollbar_selec.grid(row=7, column=0, sticky="ns", padx=(0,-10), pady=5)
  File "C:\Users\Maxi\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2550, in grid_configure
    self.tk.call(
_tkinter.TclError: bad 2nd pad value "-10": must be positive screen distance

ERROR:root:Se produjo un error: bad 2nd pad value "-1": must be positive screen distance
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 866, in main
    actualizar_interfaz()  # Llamar a la función de actualización
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 810, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\generador_mallas\Sources\main.py", line 735, in interfaz_seleccion_job
    scrollbar_selec.grid(row=7, column=0, sticky="ns", padx=(0,-1), pady=5)
  File "C:\Users\Maxi\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2550, in grid_configure
    self.tk.call(
_tkinter.TclError: bad 2nd pad value "-1": must be positive screen distance

ERROR:root:Se produjo un error: name 'start_date_entry' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 548, in main
    start_date_entry.config(state="readonly")
    ^^^^^^^^^^^^^^^^
NameError: name 'start_date_entry' is not defined

ERROR:root:Se produjo un error: name 'BooleanVar' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 486, in main
    actualizar_interfaz()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 434, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 328, in interfaz_seleccion_job
    var_seleccion = BooleanVar()
                    ^^^^^^^^^^
NameError: name 'BooleanVar' is not defined

ERROR:root:Se produjo un error: name 'BooleanVar' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 487, in main
    actualizar_interfaz()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 435, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 328, in interfaz_seleccion_job
    var_seleccion = BooleanVar()
                    ^^^^^^^^^^
NameError: name 'BooleanVar' is not defined

ERROR:root:Se produjo un error: name 'root' is not defined
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 487, in main
    actualizar_interfaz()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 435, in actualizar_interfaz
    interfaz_seleccion_job()
  File "D:\Documents\BBVA\App_new\Sources\main.py", line 330, in interfaz_seleccion_job
    check_button = Checkbutton(root, text="Seleccionar Todos", variable=var_seleccion, command=seleccionar_todos)
                               ^^^^
NameError: name 'root' is not defined

